# Generated by Django 4.2.7 on 2024-12-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_wishlist_review_productfag_notification_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
