# Generated by Django 4.2.7 on 2024-12-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='Product',
            new_name='product',
        ),
    ]
