# Generated by Django 4.2.7 on 2025-01-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_cart_product_alter_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='sub_totle',
            new_name='sub_total',
        ),
        migrations.RenameField(
            model_name='cartorderitem',
            old_name='sub_totle',
            new_name='sub_total',
        ),
        migrations.AddField(
            model_name='cartorderitem',
            name='coupon',
            field=models.ManyToManyField(blank=True, to='store.coupon'),
        ),
    ]
