# Generated by Django 4.2.7 on 2025-01-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='content',
            field=models.CharField(blank=True, default='ok', max_length=1000, null=True),
        ),
    ]
