# Generated by Django 4.2.7 on 2025-01-27 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='full_neme',
            new_name='full_name',
        ),
    ]
