# Generated by Django 4.2.7 on 2025-09-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_rename_full_neme_cartorder_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='special',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
