# Generated by Django 4.2.7 on 2025-09-06 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0002_vendor_email'),
        ('store', '0022_product_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
    ]
